baseURL: https://example.com
languageCode: en-us
defaultContentLanguage: en
title: Spatial inequalities
theme: hermit
pygmentsCodefences: yes
pygmentsUseClasses: yes
rssLimit: 10
copyright: This work is licensed under a Creative Commons Attribution-NonCommercial
  4.0 International License.
enableEmoji: yes
author:
  name: John Doe
blackfriday: {}
taxonomies:
  tag: tags
params:
  code_copy_button: yes
  dateform: Jan 2, 2006
  dateformNum: '2006-01-02'
  dateformNumTime: 2006-01-02 15:04 -0700
  dateformShort: Jan 2
  footerCopyright: ' &#183; <a href="https://creativecommons.org/licenses/by-nc/4.0/"
    target="_blank" rel="noopener">CC BY-NC 4.0</a>'
  homeSubtitle: Inequality is a major global challenge. Yet, understanding of the evolving spatial structure of inequalites at high levels of spatial resolution over time remains lacking.
  justifyContent: no
  relatedPosts: no
  social:
    - name: twitter
      url: https://twitter.com/
    - name: instagram
      url: https://instagram.com/
    - name: github
      url: https://github.com/
  themeColor: '#494f5c'
menu:
  main:
    - name: Projects
      url: projects/
      weight: 10
    - name: About
      url: about-hugo/
      weight: 20
