baseurl: https://shenoybr.github.io/hugo-goa-demo/
builddrafts: no
canonifyurls: no
languageCode: en-US
contentdir: content
layoutdir: layouts
publishdir: public
author: Erlich Bachman
title: Erlich Bachman
theme: hugo-goa
disqusShortname: https-shenoybr-github-io-hugo-goa-demo
googleAnalytics: XYZ
enableRobotsTXT: yes
params:
  author: Spatial inequalities
  dateformat: November 2, 2021
  description: ADD smth.
  
menu:
  main:
    - identifier: articles
      name: articles
      url: /articles/
      weight: 100
    - identifier: open-data
      name: open-data
      url: /open-data/
      weight: 200
    - identifier: policy-briefs
      name: policy-briefs
      url: /policy-briefs/
      weight: 300
