baseurl: https://example.com
title: Hugo Tanka Theme Demo
author: Nan Xiao
canonifyurls: yes
languagecode: en
theme: hugo-tanka
enableEmoji: yes
hasCJKLanguage: no
pygmentsstyle: vs
pygmentscodefences: yes
ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - _cache$
  - \.knit\.md$
  - \.utf8\.md$
params:
  faviconfile: images/favicon.png
  highlightjs: yes
  highlightjslanguages:
    - r
    - python
    - stan
  progressively: no
  sitename: Hugo Tanka Theme
  uselatex: yes
markup:
  goldmark:
    renderer:
      unsafe: yes
menu:
  main:
    - name: Home
      url: /docs/home
  primary:
    - name: Home
      url: /docs/home
      weight: 1
    - name: About
      url: /about/
      weight: 2
    - name: Journal Articles
      url: /docs/articles
      weight: 2
    - name: Open Data Products
      url: /docs/open-data
      weight: 2

